#pragma once

#include <gamebank/protocol/gamebank_operations.hpp>

#include <gamebank/chain/evaluator.hpp>

namespace gamebank { namespace chain {

using namespace gamebank::protocol;

GAMEBANK_DEFINE_EVALUATOR( account_create )
GAMEBANK_DEFINE_EVALUATOR( account_create_with_delegation )
GAMEBANK_DEFINE_EVALUATOR( account_update )
GAMEBANK_DEFINE_EVALUATOR( transfer )
GAMEBANK_DEFINE_EVALUATOR( transfer_to_vesting )
GAMEBANK_DEFINE_EVALUATOR( witness_update )
GAMEBANK_DEFINE_EVALUATOR( account_witness_vote )
GAMEBANK_DEFINE_EVALUATOR( account_witness_proxy )
GAMEBANK_DEFINE_EVALUATOR( withdraw_vesting )
GAMEBANK_DEFINE_EVALUATOR( set_withdraw_vesting_route )
GAMEBANK_DEFINE_EVALUATOR( comment )
GAMEBANK_DEFINE_EVALUATOR( comment_options )
GAMEBANK_DEFINE_EVALUATOR( delete_comment )
GAMEBANK_DEFINE_EVALUATOR( vote )
GAMEBANK_DEFINE_EVALUATOR( custom )
GAMEBANK_DEFINE_EVALUATOR( custom_json )
GAMEBANK_DEFINE_EVALUATOR( custom_binary )
GAMEBANK_DEFINE_EVALUATOR( pow )
GAMEBANK_DEFINE_EVALUATOR( pow2 )
GAMEBANK_DEFINE_EVALUATOR( feed_publish )
GAMEBANK_DEFINE_EVALUATOR( convert )
GAMEBANK_DEFINE_EVALUATOR( limit_order_create )
GAMEBANK_DEFINE_EVALUATOR( limit_order_cancel )
GAMEBANK_DEFINE_EVALUATOR( report_over_production )
GAMEBANK_DEFINE_EVALUATOR( limit_order_create2 )
GAMEBANK_DEFINE_EVALUATOR( escrow_transfer )
GAMEBANK_DEFINE_EVALUATOR( escrow_approve )
GAMEBANK_DEFINE_EVALUATOR( escrow_dispute )
GAMEBANK_DEFINE_EVALUATOR( escrow_release )
GAMEBANK_DEFINE_EVALUATOR( claim_account )
GAMEBANK_DEFINE_EVALUATOR( create_claimed_account )
GAMEBANK_DEFINE_EVALUATOR( request_account_recovery )
GAMEBANK_DEFINE_EVALUATOR( recover_account )
GAMEBANK_DEFINE_EVALUATOR( change_recovery_account )
GAMEBANK_DEFINE_EVALUATOR( transfer_to_savings )
GAMEBANK_DEFINE_EVALUATOR( transfer_from_savings )
GAMEBANK_DEFINE_EVALUATOR( cancel_transfer_from_savings )
GAMEBANK_DEFINE_EVALUATOR( decline_voting_rights )
GAMEBANK_DEFINE_EVALUATOR( reset_account )
GAMEBANK_DEFINE_EVALUATOR( set_reset_account )
GAMEBANK_DEFINE_EVALUATOR( claim_reward_balance )
GAMEBANK_DEFINE_EVALUATOR( delegate_vesting_shares )
GAMEBANK_DEFINE_EVALUATOR( witness_set_properties )
GAMEBANK_DEFINE_EVALUATOR( crowdfunding )
GAMEBANK_DEFINE_EVALUATOR( invest )
GAMEBANK_DEFINE_EVALUATOR( nonfungible_fund_create )
GAMEBANK_DEFINE_EVALUATOR( nonfungible_fund_transfer )
GAMEBANK_DEFINE_EVALUATOR( nonfungible_fund_put_up_for_sale )
GAMEBANK_DEFINE_EVALUATOR( nonfungible_fund_withdraw_from_sale )
GAMEBANK_DEFINE_EVALUATOR( nonfungible_fund_buy )


//define the error type of operations associated with an error message passed to FC_ASSERT

#define	ERR_OP_ACCOUNT_CREATE_INSUFFICIENT_VEST			1
#define	ERR_OP_ACCOUNT_CREATE_INSUFFICIENT_BALANCE		2
#define ERR_OP_ACCOUNT_CREATE_INSUFFICIENT_FEE			3
#define ERR_OP_ACCOUNT_UPDATE_INTERVAL					4
#define ERR_OP_POST_INTERVAL							5
#define ERR_OP_COMMENT_INTERVAL							6
#define ERR_OP_TRANSFER_INSUFFICIENT					7
#define ERR_OP_TRANSFER_TO_VEST_INSUFFICIENT			8
#define ERR_OP_WITHDRAW_RATE							9
#define ERR_OP_VOTE_DECLINE_VOTE_RIGHT					10
#define	ERR_OP_VOTE_COMMENT_NOT_ALLOW					11
#define	ERR_OP_VOTE_INTERVAL							12
#define	ERR_OP_VOTE_NO_POWER							13
#define ERR_OP_VOTE_INSUFFICIENT_POWER					14
#define	ERR_OP_VOTE_INSUFFICIENT_WEIGHT					15
#define	ERR_OP_VOTE_SIMILAR								16
#define	ERR_OP_REQUEST_ACCOUNT_RECOVERY_NOT_MATCH		17
#define	ERR_OP_REQUEST_ACCOUNT_RECOVERY_AUTHORITY		18
#define	ERR_OP_RECOVER_ACCOUNT_INTERVAL					19
#define	ERR_OP_RECOVER_ACCOUNT_NO_REQUEST				20
#define	ERR_OP_RECOVER_ACCOUNT_NOT_MATCH_OWNER			21
#define	ERR_OP_RECOVER_ACCOUNT_NO_HISTORY				22
#define	ERR_OP_CLAIM_REWARD_BALANCE_INSUFFICIENT_GBC	23
#define	ERR_OP_CLAIM_REWARD_BALANCE_INSUFFICIENT_GBD	24
#define	ERR_OP_CLAIM_REWARD_BALANCE_INSUFFICIENT_GBP	25
#define	ERR_OP_DELEGATE_VESTING_SHARES_INSUFFICIENT		26
#define	ERR_OP_DELEGATE_VESTING_SHARES_TOO_FEW			27
#define	ERR_OP_DELEGATE_VESTING_SHARES_INCREASE_INSUFFICIENT		28
#define	ERR_OP_DELEGATE_VESTING_SHARES_DECREASE_INSUFFICIENT		29
#define	ERR_OP_DELEGATE_VESTING_INVALID								30
//must add new err type below in future
#define ERR_OP_VOTE_APPROACH_CASHOUT					31

 
}} // gamebank::chain

														